[2024-06-21T13:24:49.470+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T13:24:49.577+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pythonoperator.data_cleanner_salary manual__2024-06-21T13:24:48.511545+00:00 [queued]>
[2024-06-21T13:24:49.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pythonoperator.data_cleanner_salary manual__2024-06-21T13:24:48.511545+00:00 [queued]>
[2024-06-21T13:24:49.582+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T13:24:49.597+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_cleanner_salary> on 2024-06-21 13:24:48.511545+00:00
[2024-06-21T13:24:49.602+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T13:24:49.603+0000] {standard_task_runner.py:63} INFO - Started process 453 to run task
[2024-06-21T13:24:49.603+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pythonoperator', 'data_cleanner_salary', 'manual__2024-06-21T13:24:48.511545+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/pythonoperator.py', '--cfg-path', '/tmp/tmp25b3fd8b']
[2024-06-21T13:24:49.604+0000] {standard_task_runner.py:91} INFO - Job 415: Subtask data_cleanner_salary
[2024-06-21T13:24:49.628+0000] {task_command.py:426} INFO - Running <TaskInstance: pythonoperator.data_cleanner_salary manual__2024-06-21T13:24:48.511545+00:00 [running]> on host a5e007d33222
[2024-06-21T13:24:49.693+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pythonoperator' AIRFLOW_CTX_TASK_ID='data_cleanner_salary' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T13:24:48.511545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T13:24:48.511545+00:00'
[2024-06-21T13:24:49.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T13:24:49.701+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-21T13:24:49.701+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T13:24:49.706+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pythonoperator, task_id=data_cleanner_salary, run_id=manual__2024-06-21T13:24:48.511545+00:00, execution_date=20240621T132448, start_date=20240621T132449, end_date=20240621T132449
[2024-06-21T13:24:49.735+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-21T13:24:49.747+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-21T13:24:49.749+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
