[2024-06-19T11:50:49.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T11:50:49.084+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagcomplexa.task1 manual__2024-06-19T11:50:48.709704+00:00 [queued]>
[2024-06-19T11:50:49.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagcomplexa.task1 manual__2024-06-19T11:50:48.709704+00:00 [queued]>
[2024-06-19T11:50:49.090+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T11:50:49.098+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task1> on 2024-06-19 11:50:48.709704+00:00
[2024-06-19T11:50:49.102+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=975) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T11:50:49.103+0000] {standard_task_runner.py:63} INFO - Started process 976 to run task
[2024-06-19T11:50:49.103+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagcomplexa', 'task1', 'manual__2024-06-19T11:50:48.709704+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dagcomplexa.py', '--cfg-path', '/tmp/tmpicix3_mj']
[2024-06-19T11:50:49.104+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask task1
[2024-06-19T11:50:49.133+0000] {task_command.py:426} INFO - Running <TaskInstance: dagcomplexa.task1 manual__2024-06-19T11:50:48.709704+00:00 [running]> on host 61c28926c6e1
[2024-06-19T11:50:49.183+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagcomplexa' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T11:50:48.709704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T11:50:48.709704+00:00'
[2024-06-19T11:50:49.184+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T11:50:49.193+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-19T11:50:49.193+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-19T11:50:49.199+0000] {subprocess.py:86} INFO - Output:
[2024-06-19T11:50:49.200+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-19T11:50:49.201+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T11:50:49.208+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-19T11:50:49.211+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dagcomplexa, task_id=task1, run_id=manual__2024-06-19T11:50:48.709704+00:00, execution_date=20240619T115048, start_date=20240619T115049, end_date=20240619T115049
[2024-06-19T11:50:49.218+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 976)
[2024-06-19T11:50:49.235+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T11:50:49.252+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T11:50:49.257+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
